server:
  port: 8084

spring:
  application:
    name: Users
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:problem_database
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
